### ISSUE TITLE
Kanban Board Setup for Ruby Capstone

### ISSUE THREAD

**Issue by RaoAkif** [RaoAkif/Catalogue#32]
https://github.com/users/RaoAkif/projects/5

We are a four persons team:
Team member #1: [Aaron](https://github.com/AKeeganDev)
Team member #2: [RaoAkif](https://github.com/RaoAkif)
Team member #3: [Have](https://github.com/Have-Samuel)
Team member #4: [Ivan](https://github.com/ivaan1992)

Each task for team members 1-4 is found [here](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md) and is assigned as listed above.

**Comment by ShadyShawkat** [comment]
## Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
